### PR TITLE
Issue #464

### PR DESCRIPTION
**Pull request by weshatheleopard**
As per Issue 464:

If you need socks support, in your program you should do:

```
gem 'socksify'
require 'mechanize/socks_proxy'
```
then you will be able to use `set_socks` method on Mechanize's `agent`.

### CODE REVIEW

**Comment by zenspider** [comment]
It would help if this PR was cleaned up to include the 1 commit you actually need. There shouldn't be a stream of 20 merges in your PR.

You should also drop the test fix, since it is out of scope. I've included it in #508 since that's the focus of that PR.

**Comment by weshatheleopard** [comment]
@zenspider: unfortunately I cloned this project long long time ago and overt time merges accumulated. I don't know how to re-clone it anew while keeping the history of changes on my end. Meanwhile you can click the "files changed" tab and see еру changes being limited to a single file.

Regarding the tests, I needed to demonstrate that my code passes the tests, and I couldn't do that with some tests failing. Once #508 is merged in, I will pull it in my branch and the problem will disappear.

**Comment by zenspider** [comment]
I think if you just pull master and then rebase your branch against your master it should clean it up. You'll have to force push your branch since you're changing the parent of your branch.

And no, I disagree about the tests... you have to demonstrate you don't break anything new. If master is broken (as it has been for some time, for whatever reason), you just have to match its behavior. 

Regardless, #508 is now merged.

**Comment by MatzFan** [comment]
As the originator of #464, can I ask what the current status of the PR is? If it is going to be rejected, I may try and have a go at doing a socks support PR myself (which would require fixing `net-http-persistent` to version to < 3 - see my [comment](https://github.com/sparklemotion/mechanize/issues/535#issuecomment-475817649) on related #535). Many thanks.

**Comment by zenspider** [comment]
I don't have a say... but I would suggest starting by cherry picking the relevant SHA from this PR and going from there.

**Comment by flavorjones** [comment]
Unfortunately this patch doesn't work with modern versions of `net-http-persistent`. Discussion at #464 but in the meantime I'm going to close this and decline to merge.

**Pull request closed without merging**
