### PR TITLE
CI: Using default script directive, allow Bundler to pick the gems needed

### PR DESCRIPTION
**Pull request by olleolleolle**
This is an (experimental) PR to see if we can simplify away a few of the steps and comments in the Travis configuration.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Q: Can I add 2.6.1 to the matrix, too?

**Comment by olleolleolle** [comment]
OK, the fix here would be to evict the development_dependency lines from gemspec and turn them into Bundler `gem` directives - that would make the "select the right Bundler" work.

**Comment by olleolleolle** [comment]
@leejarvis This is where I will make a fix.

**Comment by olleolleolle** [comment]
@leejarvis There.

**Comment by leejarvis** [comment]
@olleolleolle Thanks!

**Pull request merged**
