### PR TITLE
Upgrade net-http-persistent dependency (#491)

### PR DESCRIPTION
**Pull request by knu**
I guess this should have happened a long time ago.

### CODE REVIEW

**Comment by knu** [comment]
Looks like upgrading requires some changes.

**Comment by knu** [comment]
Our test suite has calls to Net::HTTP::Persistent#request_key which is gone in net-http-persistent 3.0.   Seems they were introduced in #258 but I have no idea what the intentions are and how to fix them for 3.0.

@djanowski @drbrain Any advice?

**Comment by agarcher** [comment]
My $0.02 on the tests that are using `request_key` is that they appear to be testing the internals of `Net::HTTP::Persistent`. I think the portions of the tests doing those checks can just be removed. I have a commit [here](https://github.com/agarcher/mechanize/commit/68df7d521c002773f5352bf1d89e09c2f704bf2b) with green tests (by just removing the assertions), but it doesn't maintain backwards compatibility.

This dependency is preventing us from upgrading a critical gem and may require us to stop using mechanize if this PR isn't merged.  😞

**Comment by knu** [comment]
@agarcher Would mind sending a PR to this branch?

**Comment by agarcher** [comment]
Opened https://github.com/sparklemotion/mechanize/pull/518

**Comment by knu** [comment]
@agarcher Thanks!

**Pull request merged**
